services:
  web-app:
    build:
      context: .
    ports:
      - '8000:8000'
    volumes:
      - .:/code
    environment:
      - DB_HOST=database
      - DB_NAME=db_name
      - DB_USER=dbuser
      - DB_PASS=pass

    depends_on:
      - database

  database:
    image: postgres
    environment:
      - POSTGRES_DB=db_name
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass